version: "3.8"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ${ASSETS-/opt/docker/homer/assets}:/www/assets
    ports:
      - ${PORT-8080}:8080
    user: ${PUID-1000}:${PGID-1000}
    environment:
      - INIT_ASSETS=${INIT_ASSETS-1} 