version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - ${PORT}:80
    volumes:
      - ${DATA_DIR}:/srv
      - ${WORK_DIR}/database:/database
      - ${WORK_DIR}/config:/config
    environment:
      - FB_BASEURL=/filebrowser
      - PUID=${PUID}
      - PGID=${PGID}
    restart: always