version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser
    user: "${PUID-1000}:${PGID-1000}"
    ports:
      - ${PORT-8081}:80
    volumes:
      - ${DATA_DIR}:/srv
      - ${WORK_DIR}/database:/database
      - ${WORK_DIR}/config:/config
    environment:
      - FB_BASEURL=${FB_BASEURL-/filebrowser}
      - PUID=${PUID-1000}
      - PGID=${PGID-1000}
    restart: always